include: package:flutter_lints/flutter.yaml

linter:

  rules:
    always_use_package_imports: true
    throw_in_finally: true
    unnecessary_await_in_return: true
    unnecessary_this: true
    unnecessary_const: true
    unnecessary_final: true
    unnecessary_constructor_name: true
    unnecessary_new: true
    unnecessary_overrides: true
    
    prefer_single_quotes: true
    prefer_void_to_null: true

    avoid_print: true
    avoid_empty_else: true
    avoid_annotating_with_dynamic: true
    avoid_multiple_declarations_per_line: true
    avoid_returning_null: true
    avoid_returning_this: true
    await_only_futures: true
    camel_case_types: true
    curly_braces_in_flow_control_structures: true
    empty_catches: true
    eol_at_end_of_file: true

    no_duplicate_case_values: true
    valid_regexps: true
    flutter_style_todos: true
    lines_longer_than_80_chars: true
    non_constant_identifier_names: true
    package_api_docs: true
